apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - image: quay.io/dholler/simpleapp
        name: simpleapp
        ports:
        - containerPort: 5000
